-- MySQL Script generated by MySQL Workbench
-- Wed May 14 15:16:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`atividades_produtivas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atividades_produtivas` (
  `idatividades_produtivas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idatividades_produtivas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `tipo_atividade` ENUM('Curso', 'Oficina') NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` TEXT NOT NULL,
  `local` VARCHAR(255) NOT NULL,
  `foto_banner` VARCHAR(255) NULL DEFAULT NULL,
  `instituicao` VARCHAR(255) NOT NULL,
  `publico_alvo` ENUM('Geral', 'Interno', 'Comunidade', 'Estudantes', 'Idosos') NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `data_insc_inicio` DATE NOT NULL,
  `data_insc_fim` DATE NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT '1',
  `turno` ENUM('Manhã', 'Tarde', 'Noite') NOT NULL,
  `max_pessoas` INT NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_de_horta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_de_horta` (
  `idtipo_de_horta` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtipo_de_horta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`unidades_ensino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unidades_ensino` (
  `idunidade_ensino` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idunidade_ensino`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `escolaridade_id` INT NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `escolaridade` ENUM('Sem escolaridade', 'Ensino fundamental incompleto', 'Ensino fundamental completo', 'Ensino médio incompleto', 'Ensino médio completo', 'Ensino superior incompleto', 'Ensino superior completo', 'Pós graduação') NULL DEFAULT NULL,
  PRIMARY KEY (`idpessoa`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `idpessoa` INT NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `data_criacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ativo` TINYINT NOT NULL DEFAULT '1',
  `is_tecnico` TINYINT NOT NULL DEFAULT '0',
  `matricula` VARCHAR(255) NULL DEFAULT NULL,
  `cad_unico` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `unique_pessoa_idpessoa` (`idpessoa` ASC) VISIBLE,
  INDEX `fk_usuario_pessoa_idx` (`idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_pessoa`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `mydb`.`pessoa` (`idpessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`horta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`horta` (
  `idhorta` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `unidade_ensino_idunidade_ensino` INT NOT NULL,
  `tam_area_prod` FLOAT NOT NULL,
  `tipo_area` VARCHAR(255) NOT NULL,
  `atividades_produtivas` INT NOT NULL,
  `carac_grupo` VARCHAR(255) NULL DEFAULT NULL,
  `turma` VARCHAR(255) NULL DEFAULT NULL,
  `qnt_pessoas` INT NOT NULL,
  `atividade_desc` VARCHAR(255) NOT NULL,
  `apoio` VARCHAR(255) NULL DEFAULT NULL,
  `img_cam` VARCHAR(255) NOT NULL,
  `encontro_data` DATE NULL DEFAULT NULL,
  `data_criacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tipo_de_horta` INT NOT NULL,
  `status` ENUM('Em análise', 'Aprovada', 'Reprovada', 'Finalizada') NOT NULL DEFAULT 'Em análise',
  PRIMARY KEY (`idhorta`),
  INDEX `fk_horta_unificada_atividades_produtivas_idx` (`atividades_produtivas` ASC) VISIBLE,
  INDEX `fk_horta_unificada_unidades_ensino_idx` (`unidade_ensino_idunidade_ensino` ASC) VISIBLE,
  INDEX `fk_horta_unificada_usuarios_idx` (`idusuario` ASC) VISIBLE,
  INDEX `fk_horta_tipo_de_horta1_idx` (`tipo_de_horta` ASC) VISIBLE,
  CONSTRAINT `fk_horta_tipo_de_horta1`
    FOREIGN KEY (`tipo_de_horta`)
    REFERENCES `mydb`.`tipo_de_horta` (`idtipo_de_horta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_horta_unificada_atividades_produtivas`
    FOREIGN KEY (`atividades_produtivas`)
    REFERENCES `mydb`.`atividades_produtivas` (`idatividades_produtivas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_horta_unificada_unidades_ensino`
    FOREIGN KEY (`unidade_ensino_idunidade_ensino`)
    REFERENCES `mydb`.`unidades_ensino` (`idunidade_ensino`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_horta_unificada_usuarios`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`inscricao_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inscricao_curso` (
  `idinscricao_curso` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idcurso` INT NOT NULL,
  `data_inscricao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idinscricao_curso`),
  INDEX `fk_inscricao_curso_usuario_idx` (`idusuario` ASC) VISIBLE,
  INDEX `fk_inscricao_curso_curso_idx` (`idcurso` ASC) VISIBLE,
  CONSTRAINT `fk_inscricao_curso_curso`
    FOREIGN KEY (`idcurso`)
    REFERENCES `mydb`.`cursos` (`idcurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscricao_curso_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
