-- MySQL Script generated by MySQL Workbench
-- Sun May  4 23:34:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`atividades_produtivas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atividades_produtivas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`form_inscricao_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`form_inscricao_cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(255) NOT NULL,
  `idade` INT NOT NULL,
  `escolaridade` VARCHAR(255) NOT NULL,
  `profissao` VARCHAR(255) NOT NULL,
  `ocupacao_atual` VARCHAR(255) NOT NULL,
  `atividade_produtiva` VARCHAR(255) NOT NULL,
  `interesse_curso` VARCHAR(255) NULL DEFAULT NULL,
  `img_cam` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `id` INT NOT NULL,
  `nome_curso` VARCHAR(45) NOT NULL,
  `form_inscricao_cursos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cursos_form_inscricao_cursos1_idx` (`form_inscricao_cursos_id` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_form_inscricao_cursos1`
    FOREIGN KEY (`form_inscricao_cursos_id`)
    REFERENCES `mydb`.`form_inscricao_cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`escolaridade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`unidades_ensino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unidades_ensino` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `data_criacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `escolaridade_id` INT NOT NULL,
  `ativo` TINYINT NULL DEFAULT NULL,
  `cad_unico` TINYINT NULL DEFAULT NULL,
  `cad_unico_number` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_escolaridade1_idx` (`escolaridade_id` ASC) VISIBLE,
  CONSTRAINT `escolaridade`
    FOREIGN KEY (`escolaridade_id`)
    REFERENCES `mydb`.`escolaridade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_de_horta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_de_horta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`horta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`horta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `funcao_uni_ensino` VARCHAR(255) NULL DEFAULT NULL,
  `profissao` VARCHAR(255) NULL DEFAULT NULL,
  `ocu_principal` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `outro_endereco` VARCHAR(255) NULL DEFAULT NULL,
  `unidade_ensino_id` INT NOT NULL,
  `tam_area_prod` FLOAT NOT NULL,
  `tipo_de_area` VARCHAR(255) NOT NULL,
  `atividades_produtivas_id` INT NOT NULL,
  `carac_grupo` VARCHAR(255) NULL DEFAULT NULL,
  `turma` VARCHAR(255) NULL DEFAULT NULL,
  `qnt_pessoas` INT NOT NULL,
  `atividade_desc` VARCHAR(255) NOT NULL,
  `apoio` VARCHAR(255) NULL DEFAULT NULL,
  `img_cam` VARCHAR(255) NOT NULL,
  `encontro_data` DATE NULL DEFAULT NULL,
  `data_criacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuarios_id` INT NOT NULL,
  `tipo_de_horta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_horta_unificada_atividades_produtivas_idx` (`atividades_produtivas_id` ASC) VISIBLE,
  INDEX `fk_horta_unificada_unidades_ensino_idx` (`unidade_ensino_id` ASC) VISIBLE,
  INDEX `fk_horta_unificada_usuarios_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_horta_tipo_de_horta1_idx` (`tipo_de_horta_id` ASC) VISIBLE,
  CONSTRAINT `fk_horta_unificada_atividades_produtivas`
    FOREIGN KEY (`atividades_produtivas_id`)
    REFERENCES `mydb`.`atividades_produtivas` (`id`),
  CONSTRAINT `fk_horta_unificada_unidades_ensino`
    FOREIGN KEY (`unidade_ensino_id`)
    REFERENCES `mydb`.`unidades_ensino` (`id`),
  CONSTRAINT `fk_horta_unificada_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`),
  CONSTRAINT `fk_horta_tipo_de_horta1`
    FOREIGN KEY (`tipo_de_horta_id`)
    REFERENCES `mydb`.`tipo_de_horta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tecnicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(255) NOT NULL,
  `matricula` VARCHAR(255) NOT NULL,
  `data_criacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `password` VARCHAR(255) NOT NULL,
  `ativo` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = '	\\n				';


-- -----------------------------------------------------
-- Table `mydb`.`hortas_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hortas_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tecnico_id` INT NOT NULL,
  `data_visita` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(45) NOT NULL,
  `obs` VARCHAR(255) NULL DEFAULT NULL,
  `tecnicos_id` INT NOT NULL,
  `horta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hortas_ensino_status_tecnicos1_idx` (`tecnico_id` ASC) VISIBLE,
  INDEX `fk_hortas_status_tecnicos1_idx` (`tecnicos_id` ASC) VISIBLE,
  INDEX `fk_hortas_status_horta1_idx` (`horta_id` ASC) VISIBLE,
  CONSTRAINT `fk_hortas_status_tecnicos1`
    FOREIGN KEY (`tecnicos_id`)
    REFERENCES `mydb`.`tecnicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hortas_status_horta1`
    FOREIGN KEY (`horta_id`)
    REFERENCES `mydb`.`horta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
